version: '3.9'

services:
  mongodb:
    image: mongo:5.0.6
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: du
    ports:
      - 27444:27017
    volumes:
      - mongo-db:/data/db
    networks:
      - mongo-network

volumes:
  mongo-db:

networks:
  mongo-network:
    driver: bridge
