version: '3.9'

services:
  mongodb:
    image: mongo:5.0.6
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: du
    ports:
      - 27017:27017
    volumes:
      - mongo-db:/data/db

  api:
    depends_on:
      - mongodb
    build:
      context: './'
      args:
        - NODE_ENV=development
    container_name: "api-dev"
    env_file:
      - ./.env
    environment:
        - PORT=4000
        - NODE_ENV=development
        - MONGODB_USER=root
        - MONGODB_PASSWORD=123456
        - MONGODB_DATABASE=du
        - MONGODB_PORT=27017
        - MONGODB_HOST=mongodb
    restart: on-failure
    ports:
      - 4000:4000

volumes:
  mongo-db:
